//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tamagawa.EnmityPlugin {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tamagawa.EnmityPlugin.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Current: v{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   New release of EnmityPlugin is available! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NewVersionIsAvailable {
            get {
                return ResourceManager.GetString("NewVersionIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open release site now? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OpenSiteNow {
            get {
                return ResourceManager.GetString("OpenSiteNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not find FFXIV Process.ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ProcessNotFound {
            get {
                return ResourceManager.GetString("ProcessNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memory scanning started. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StartScanning {
            get {
                return ResourceManager.GetString("StartScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memory scanning stopped. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StopScanning {
            get {
                return ResourceManager.GetString("StopScanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update: v{0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The plugin is up to date. (v{0}) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UpdateNotFound {
            get {
                return ResourceManager.GetString("UpdateNotFound", resourceCulture);
            }
        }
    }
}
